#!/usr/bin/env bash

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

echo -e "\n=> Starting script/cibuild"

export ENVIRONMENT="testing"

script/test