#!/usr/bin/env bash

# script/server: Launch the application and any extra required processes
#                locally.
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

echo -e "\n=> Starting script/server"

test -z "$ENVIRONMENT" &&
  ENVIRONMENT='development'

if ! [[ "$ENVIRONMENT" = development ]]; then
  pipx ensurepath > /dev/null && source $HOME/.profile
fi

echo -e "\n=> Starting the Fixed That For You bot..." &
poetry run python main.py