#!/usr/bin/env bash

# script/server: Launch the application and any extra required processes
#                locally.
trap "trap - SIGTERM && kill -- -$$" SIGINT SIGTERM EXIT

set -e

cd "$(dirname "$0")/.."

echo -e "\n=> Starting script/server"

test -z "$ENVIRONMENT" &&
  ENVIRONMENT='development'

echo -e "\n=> Starting the Fixed That For You bot..." &
python main.py