#!/usr/bin/env bash

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo -e "\n=> Starting script/update"

echo -e "\n=> Finished script/update\n"